singleServerConfig:
  address: "redis://redis-12898.c339.eu-west-3-1.ec2.redns.redis-cloud.com:12898"
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}
  connectionMinimumIdleSize: 4
  connectionPoolSize: 16
  subscriptionConnectionPoolSize: 2
  idleConnectionTimeout: 30000 #ms

